// RUN: ttl-opt --canonicalize %s | FileCheck %s

module {
  func.func @const_dim() -> !ttl.int {
    %0 = "ttl.tensor_empty"() : () -> !ttl.tensor<4x3x!ttl.float>
    %1 = "ttl.const_int"() <{constVal = 1 : i32}> : () -> !ttl.int
    %2 = "ttl.dim"(%0, %1) : (!ttl.tensor<4x3x!ttl.float>, !ttl.int) -> !ttl.int
    "ttl.return"(%2) : (!ttl.int) -> ()
  }
  func.func @const_param_dim(%arg0: !ttl.tensor<5x2x!ttl.float>) -> !ttl.int {
    %0 = "ttl.const_int"() <{constVal = 0 : i32}> : () -> !ttl.int
    %1 = "ttl.dim"(%arg0, %0) : (!ttl.tensor<5x2x!ttl.float>, !ttl.int) -> !ttl.int
    "ttl.return"(%1) : (!ttl.int) -> ()
  }
  func.func @non_const_dim(%arg0: !ttl.int) -> !ttl.int {
    %0 = "ttl.tensor_empty"() : () -> !ttl.tensor<7x8x!ttl.float>
    %1 = "ttl.dim"(%0, %arg0) : (!ttl.tensor<7x8x!ttl.float>, !ttl.int) -> !ttl.int
    "ttl.return"(%1) : (!ttl.int) -> ()
  }
}

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   func.func @const_dim() -> !ttl.int {
// CHECK:           %[[VAL_0:.*]] = "ttl.const_int"() <{constVal = 3 : i32}> : () -> !ttl.int
// CHECK:           %[[VAL_1:.*]] = "ttl.tensor_empty"() : () -> !ttl.tensor<4x3x!ttl.float>
// CHECK:           "ttl.return"(%[[VAL_0]]) : (!ttl.int) -> ()
// CHECK:         }

// CHECK-LABEL:   func.func @const_param_dim(
// CHECK-SAME:                               %[[VAL_0:.*]]: !ttl.tensor<5x2x!ttl.float>) -> !ttl.int {
// CHECK:           %[[VAL_1:.*]] = "ttl.const_int"() <{constVal = 5 : i32}> : () -> !ttl.int
// CHECK:           "ttl.return"(%[[VAL_1]]) : (!ttl.int) -> ()
// CHECK:         }

// CHECK-LABEL:   func.func @non_const_dim(
// CHECK-SAME:                             %[[VAL_0:.*]]: !ttl.int) -> !ttl.int {
// CHECK:           %[[VAL_1:.*]] = "ttl.tensor_empty"() : () -> !ttl.tensor<7x8x!ttl.float>
// CHECK:           %[[VAL_2:.*]] = "ttl.dim"(%[[VAL_1]], %[[VAL_0]]) : (!ttl.tensor<7x8x!ttl.float>, !ttl.int) -> !ttl.int
// CHECK:           "ttl.return"(%[[VAL_2]]) : (!ttl.int) -> ()
// CHECK:         }

